# AUTO-GENERATED by scripts/gen_configs.py -- do not edit by hand.
# YOLO-World-S finetune on COCO with the vision backbone swapped to yolov8s.
#
# Only the backbone changes between variants; the text branch, YOLOWorldPAFPN
# neck (text-guided), YOLOWorldHead, optimiser and COCO recipe are identical.
# Backbone P3/P4/P5 channels for yolov8s = [128, 256, 512] (probed live by gen_configs.py).
_base_ = ('/home/huanghai/yolo_world_test/third_party/mmyolo/configs/yolov8/yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco.py')
custom_imports = dict(
    imports=['yolo_world', 'adapters'],
    allow_failed_imports=False)

# -------------------------------------------------------------- hyper-params
num_classes = 80
num_training_classes = 80
max_epochs = 80
close_mosaic_epochs = 10
save_epoch_intervals = 5
text_channels = 512
base_lr = 2e-4
weight_decay = 0.05
train_batch_size_per_gpu = 16
persistent_workers = True
mixup_prob = 0.15
copypaste_prob = 0.3

# backbone-specific (probed)
backbone_arch = 'yolov8s'
backbone_ckpt = '/home/huanghai/yolo_world_test/data/weights/yolov8s.pt'
neck_in_channels = [128, 256, 512]
neck_out_channels = [128, 256, 512]
neck_embed_channels = [64, 128, 256]
neck_num_heads = [2, 4, 8]

# CLIP text encoder + COCO data (absolute paths; offline)
text_model_name = '/home/huanghai/yolo_world_test/data/weights/clip-vit-base-patch32'
data_root = '/home/huanghai/yolo_world_test/data/coco'
class_text_path = '/home/huanghai/yolo_world_test/data/texts/coco_class_texts.json'
val_ann_file = '/home/huanghai/yolo_world_test/data/coco/annotations/instances_val2017.json'

# ------------------------------------------------------------------- model
model = dict(
    type='YOLOWorldDetector',
    mm_neck=True,
    num_train_classes=num_training_classes,
    num_test_classes=num_classes,
    data_preprocessor=dict(type='YOLOWDetDataPreprocessor'),
    backbone=dict(
        _delete_=True,
        type='MultiModalYOLOBackbone',
        image_model=dict(
            type='UltralyticsYOLOBackbone',
            arch=backbone_arch,
            checkpoint=backbone_ckpt),
        text_model=dict(
            type='HuggingCLIPLanguageBackbone',
            model_name=text_model_name,
            frozen_modules=['all'])),
    neck=dict(
        type='YOLOWorldPAFPN',
        in_channels=neck_in_channels,
        out_channels=neck_out_channels,
        widen_factor=1.0,
        guide_channels=text_channels,
        embed_channels=neck_embed_channels,
        num_heads=neck_num_heads,
        block_cfg=dict(type='MaxSigmoidCSPLayerWithTwoConv')),
    bbox_head=dict(
        type='YOLOWorldHead',
        head_module=dict(
            type='YOLOWorldHeadModule',
            use_bn_head=True,
            embed_dims=text_channels,
            num_classes=num_training_classes,
            in_channels=neck_in_channels,
            widen_factor=1.0)),
    train_cfg=dict(assigner=dict(num_classes=num_training_classes)))

# ----------------------------------------------------------------- dataset
text_transform = [
    dict(type='RandomLoadText',
         num_neg_samples=(num_classes, num_classes),
         max_num_samples=num_training_classes,
         padding_to_max=True,
         padding_value=''),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                    'flip_direction', 'texts'))
]
mosaic_affine_transform = [
    dict(type='MultiModalMosaic',
         img_scale=_base_.img_scale,
         pad_val=114.0,
         pre_transform=_base_.pre_transform),
    dict(type='YOLOv5CopyPaste', prob=copypaste_prob),
    dict(type='YOLOv5RandomAffine',
         max_rotate_degree=0.0,
         max_shear_degree=0.0,
         max_aspect_ratio=100.,
         scaling_ratio_range=(1 - _base_.affine_scale, 1 + _base_.affine_scale),
         border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2),
         border_val=(114, 114, 114),
         min_area_ratio=_base_.min_area_ratio,
         use_mask_refine=_base_.use_mask2refine)
]
train_pipeline = [
    *_base_.pre_transform,
    *mosaic_affine_transform,
    dict(type='YOLOv5MultiModalMixUp',
         prob=mixup_prob,
         pre_transform=[*_base_.pre_transform, *mosaic_affine_transform]),
    *_base_.last_transform[:-1],
    *text_transform
]
train_pipeline_stage2 = [*_base_.train_pipeline_stage2[:-1], *text_transform]
coco_train_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root=data_root,
        ann_file='annotations/instances_train2017.json',
        data_prefix=dict(img='train2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path=class_text_path,
    pipeline=train_pipeline)
train_dataloader = dict(
    persistent_workers=persistent_workers,
    batch_size=train_batch_size_per_gpu,
    collate_fn=dict(type='yolow_collate'),
    dataset=coco_train_dataset)

test_pipeline = [
    *_base_.test_pipeline[:-1],
    dict(type='LoadText'),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                    'scale_factor', 'pad_param', 'texts'))
]
coco_val_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root=data_root,
        ann_file='annotations/instances_val2017.json',
        data_prefix=dict(img='val2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path=class_text_path,
    pipeline=test_pipeline)
val_dataloader = dict(dataset=coco_val_dataset)
test_dataloader = val_dataloader

# ---------------------------------------------------------------- schedule
default_hooks = dict(
    param_scheduler=dict(scheduler_type='linear', lr_factor=0.01,
                         max_epochs=max_epochs),
    checkpoint=dict(max_keep_ckpts=2, save_best='auto',
                    interval=save_epoch_intervals))
custom_hooks = [
    dict(type='EMAHook', ema_type='ExpMomentumEMA', momentum=0.0001,
         update_buffers=True, strict_load=False, priority=49),
    dict(type='mmdet.PipelineSwitchHook',
         switch_epoch=max_epochs - close_mosaic_epochs,
         switch_pipeline=train_pipeline_stage2)
]
train_cfg = dict(
    max_epochs=max_epochs,
    val_interval=5,
    dynamic_intervals=[((max_epochs - close_mosaic_epochs),
                        _base_.val_interval_stage2)])
optim_wrapper = dict(
    optimizer=dict(_delete_=True, type='AdamW', lr=base_lr,
                   weight_decay=weight_decay,
                   batch_size_per_gpu=train_batch_size_per_gpu),
    paramwise_cfg=dict(custom_keys={
        'backbone.text_model': dict(lr_mult=0.01),
        'logit_scale': dict(weight_decay=0.0)}),
    constructor='YOLOWv5OptimizerConstructor')

# -------------------------------------------------------------- evaluation
val_evaluator = dict(
    _delete_=True,
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file=val_ann_file,
    metric='bbox')
test_evaluator = val_evaluator
