#!/usr/bin/env python
"""Generate one self-contained YOLO-World finetune config per backbone variant.

Each config inherits the *unmodified* MMYOLO YOLOv8-s base (for the data
pipeline / schedule machinery) and then swaps **only** the vision backbone for
an Ultralytics YOLO (v8/v9/v10/v11/v12/v26) via ``UltralyticsYOLOBackbone``.
Everything else - the YOLO-World text branch, the text-guided ``YOLOWorldPAFPN``
neck, the contrastive ``YOLOWorldHead``, the optimiser and the COCO recipe -
is held identical across variants, so the backbone is the only variable.

The neck/head channel widths are read *live* from each backbone (a dummy
forward pass through the adapter), guaranteeing the configs match reality even
for architectures whose P3/P4/P5 widths differ from YOLOv8 (e.g. v9-s is
[128,192,256]; 11/12/26-s are [256,256,512]).

Run inside the venv with scripts/env.sh sourced:
    python scripts/gen_configs.py
"""
import os
from string import Template

ROOT = "/home/huanghai/yolo_world_test"
BASE = (f"{ROOT}/third_party/mmyolo/configs/yolov8/"
        "yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco.py")
DATA_ROOT = f"{ROOT}/data/coco"
TEXTS = f"{ROOT}/data/texts/coco_class_texts.json"
CLIP_DIR = f"{ROOT}/data/weights/clip-vit-base-patch32"
WEIGHTS_DIR = f"{ROOT}/data/weights"
CONFIG_DIR = f"{ROOT}/configs"

# Ultralytics architecture stems to benchmark. v8s is the YOLO-World baseline.
VARIANTS = ["yolov8s", "yolov9s", "yolov10s", "yolo11s", "yolo12s", "yolo26s"]

# Text-fusion capacity of the YOLOWorldPAFPN, held FIXED across all variants so
# only the backbone differs. These equal the *effective* (post widen_factor=0.5)
# values of the canonical YOLO-World-s config: embed/heads = 32 channels/head.
NECK_EMBED_CHANNELS = [64, 128, 256]
NECK_NUM_HEADS = [2, 4, 8]

TEMPLATE = Template('''# AUTO-GENERATED by scripts/gen_configs.py -- do not edit by hand.
# YOLO-World-S finetune on COCO with the vision backbone swapped to $ARCH.
#
# Only the backbone changes between variants; the text branch, YOLOWorldPAFPN
# neck (text-guided), YOLOWorldHead, optimiser and COCO recipe are identical.
# Backbone P3/P4/P5 channels for $ARCH = $CH (probed live by gen_configs.py).
_base_ = ('$BASE')
custom_imports = dict(
    imports=['yolo_world', 'adapters'],
    allow_failed_imports=False)

# -------------------------------------------------------------- hyper-params
num_classes = 80
num_training_classes = 80
max_epochs = 80
close_mosaic_epochs = 10
save_epoch_intervals = 5
text_channels = 512
base_lr = 2e-4
weight_decay = 0.05
train_batch_size_per_gpu = 16
persistent_workers = True
mixup_prob = 0.15
copypaste_prob = 0.3

# backbone-specific (probed)
backbone_arch = '$ARCH'
backbone_ckpt = $CKPT
neck_in_channels = $CH
neck_out_channels = $CH
neck_embed_channels = $EMBED
neck_num_heads = $HEADS

# CLIP text encoder + COCO data (absolute paths; offline)
text_model_name = '$CLIP_DIR'
data_root = '$DATA_ROOT'
class_text_path = '$TEXTS'
val_ann_file = '$DATA_ROOT/annotations/instances_val2017.json'

# ------------------------------------------------------------------- model
model = dict(
    type='YOLOWorldDetector',
    mm_neck=True,
    num_train_classes=num_training_classes,
    num_test_classes=num_classes,
    data_preprocessor=dict(type='YOLOWDetDataPreprocessor'),
    backbone=dict(
        _delete_=True,
        type='MultiModalYOLOBackbone',
        image_model=dict(
            type='UltralyticsYOLOBackbone',
            arch=backbone_arch,
            checkpoint=backbone_ckpt),
        text_model=dict(
            type='HuggingCLIPLanguageBackbone',
            model_name=text_model_name,
            frozen_modules=['all'])),
    neck=dict(
        type='YOLOWorldPAFPN',
        in_channels=neck_in_channels,
        out_channels=neck_out_channels,
        widen_factor=1.0,
        guide_channels=text_channels,
        embed_channels=neck_embed_channels,
        num_heads=neck_num_heads,
        block_cfg=dict(type='MaxSigmoidCSPLayerWithTwoConv')),
    bbox_head=dict(
        type='YOLOWorldHead',
        head_module=dict(
            type='YOLOWorldHeadModule',
            use_bn_head=True,
            embed_dims=text_channels,
            num_classes=num_training_classes,
            in_channels=neck_in_channels,
            widen_factor=1.0)),
    train_cfg=dict(assigner=dict(num_classes=num_training_classes)))

# ----------------------------------------------------------------- dataset
text_transform = [
    dict(type='RandomLoadText',
         num_neg_samples=(num_classes, num_classes),
         max_num_samples=num_training_classes,
         padding_to_max=True,
         padding_value=''),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                    'flip_direction', 'texts'))
]
mosaic_affine_transform = [
    dict(type='MultiModalMosaic',
         img_scale=_base_.img_scale,
         pad_val=114.0,
         pre_transform=_base_.pre_transform),
    dict(type='YOLOv5CopyPaste', prob=copypaste_prob),
    dict(type='YOLOv5RandomAffine',
         max_rotate_degree=0.0,
         max_shear_degree=0.0,
         max_aspect_ratio=100.,
         scaling_ratio_range=(1 - _base_.affine_scale, 1 + _base_.affine_scale),
         border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2),
         border_val=(114, 114, 114),
         min_area_ratio=_base_.min_area_ratio,
         use_mask_refine=_base_.use_mask2refine)
]
train_pipeline = [
    *_base_.pre_transform,
    *mosaic_affine_transform,
    dict(type='YOLOv5MultiModalMixUp',
         prob=mixup_prob,
         pre_transform=[*_base_.pre_transform, *mosaic_affine_transform]),
    *_base_.last_transform[:-1],
    *text_transform
]
train_pipeline_stage2 = [*_base_.train_pipeline_stage2[:-1], *text_transform]
coco_train_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root=data_root,
        ann_file='annotations/instances_train2017.json',
        data_prefix=dict(img='train2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path=class_text_path,
    pipeline=train_pipeline)
train_dataloader = dict(
    persistent_workers=persistent_workers,
    batch_size=train_batch_size_per_gpu,
    collate_fn=dict(type='yolow_collate'),
    dataset=coco_train_dataset)

test_pipeline = [
    *_base_.test_pipeline[:-1],
    dict(type='LoadText'),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                    'scale_factor', 'pad_param', 'texts'))
]
coco_val_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root=data_root,
        ann_file='annotations/instances_val2017.json',
        data_prefix=dict(img='val2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path=class_text_path,
    pipeline=test_pipeline)
val_dataloader = dict(dataset=coco_val_dataset)
test_dataloader = val_dataloader

# ---------------------------------------------------------------- schedule
default_hooks = dict(
    param_scheduler=dict(scheduler_type='linear', lr_factor=0.01,
                         max_epochs=max_epochs),
    checkpoint=dict(max_keep_ckpts=2, save_best='auto',
                    interval=save_epoch_intervals))
custom_hooks = [
    dict(type='EMAHook', ema_type='ExpMomentumEMA', momentum=0.0001,
         update_buffers=True, strict_load=False, priority=49),
    dict(type='mmdet.PipelineSwitchHook',
         switch_epoch=max_epochs - close_mosaic_epochs,
         switch_pipeline=train_pipeline_stage2)
]
train_cfg = dict(
    max_epochs=max_epochs,
    val_interval=5,
    dynamic_intervals=[((max_epochs - close_mosaic_epochs),
                        _base_.val_interval_stage2)])
optim_wrapper = dict(
    optimizer=dict(_delete_=True, type='AdamW', lr=base_lr,
                   weight_decay=weight_decay,
                   batch_size_per_gpu=train_batch_size_per_gpu),
    paramwise_cfg=dict(custom_keys={
        'backbone.text_model': dict(lr_mult=0.01),
        'logit_scale': dict(weight_decay=0.0)}),
    constructor='YOLOWv5OptimizerConstructor')

# -------------------------------------------------------------- evaluation
val_evaluator = dict(
    _delete_=True,
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file=val_ann_file,
    metric='bbox')
test_evaluator = val_evaluator
''')


def probe_channels(arch):
    from adapters import UltralyticsYOLOBackbone
    bb = UltralyticsYOLOBackbone(arch=arch)
    return list(bb.out_channels)


def main():
    os.makedirs(CONFIG_DIR, exist_ok=True)
    summary = []
    for arch in VARIANTS:
        ch = probe_channels(arch)
        ckpt = f"{WEIGHTS_DIR}/{arch}.pt"
        # bake the abs path; the adapter falls back to random init if absent,
        # so configs are valid before the .pt files are downloaded.
        ckpt_literal = repr(ckpt)
        text = TEMPLATE.substitute(
            ARCH=arch,
            BASE=BASE,
            CKPT=ckpt_literal,
            CH=repr(ch),
            EMBED=repr(NECK_EMBED_CHANNELS),
            HEADS=repr(NECK_NUM_HEADS),
            CLIP_DIR=CLIP_DIR,
            DATA_ROOT=DATA_ROOT,
            TEXTS=TEXTS,
        )
        out = f"{CONFIG_DIR}/yoloworld_s_{arch}_coco.py"
        with open(out, "w") as f:
            f.write(text)
        summary.append((arch, ch, out))
        print(f"[gen] {arch:9s} channels={ch}  ->  {out}")
    print(f"\n[gen] wrote {len(summary)} configs to {CONFIG_DIR}")


if __name__ == "__main__":
    main()
